import React, { useState } from 'react';
import { Button } from '@chakra-ui/button';
import { VStack, Text } from '@chakra-ui/layout';
import { keyframes, usePrefersReducedMotion } from '@chakra-ui/react';
const spin = keyframes`
  from { transform: scale(0.1); }
  to { transform: scale(1.5); }
`;

const BtnConciencia = props => {
  const prefersReducedMotion = usePrefersReducedMotion();
  const animation = prefersReducedMotion
    ? undefined
    : `${spin} infinite 5s linear`;
  const [index, setIndex] = useState(0);
  const mensaje = [
    '',
    'Ah, la curiosidad...',
    '¿Necesitabas saber que era esto, no?',
    'Ok...',
    'Este botón llama a tu conciencia.',
    'No es una práctica recomendable.',
    'Pero, si no queda otra.',
    'Clikeá con responsabilidad',
    'RESPONSABILIDAD',
    '',
    '',
    '...',
    'Hey',
    '¡HEY!',
    'No te dijeron "¿CON RESPONSABILIDAD?',
    '¿Siempre hacés lo que querés?',
    'Bueno...',
    'Insistís.',
    'Esto viene para largo.',
    'Estemmmm....',
    'Ya estaría...',
    'En fin.',
    'Juguemos a algo ya que estamos acá',
    `Tiraste papel picado 🎉 ${props.contador} veces...`,
    '¿No te alcanzaba con ser más feliz, no?',
    '¿Como son los human@s, eh?',
    '¿Tenías que clickear acá también?',
    'Te avisaron que me ibas a llamar.',
    'Ahora estamos aca ambos...',
    'MATANDO LA PRODUCTIVIDAD.',
    'Tu empleador no debe estar feliz.',
    '¿No te interpela esta afirmación?',
    '¿Le mando un mail?',
    'Quizás es mejor esto.',
    'Que estar pasando Stories de IG...',
    'O Tik Tok, claro',
    'Gente bailandole al celular ...raro por lo menos.',
    'Si sos recruiter, está todo bien',
    'Estás haciendo tu trabajo',
    'Ponele...',
    '¿Deberías evaluar al postulante con esta pavada?',
    'No. Cerrá y corré.',
    'Ah, seguis acá',
    'Bueno mirá, como tu conciencia.',
    'Te recomiendo, por lo menos darle una oportunidad',
    'Es emprendedor (literal)',
    'Proactivo',
    'Ama la industria',
    'Y busca mejorar sus habilidades técnicas todo el tiempo',
    'En fin. Esto parece una venta',
    '¿Tendrá algo para ofrecer?',
    'Ahi es tema tuyo...',
    'Lo único que puedo asegurarte...',
    'Es que la moral del equipo no la deja caer nunca.🤡',
    'Entonces',
    'Quedaría lindo en redes ',
    '"Ayudé a esta persona en sus 40"',
    '"En su proceso de reconversión laboral en IT"',
    '😐',
    '¿Viste Inception?',
    'No, dejá... Nada ',
    'Volviendo al tema de la pavada.',
    'Casi, casi le pone de nombre...',
    '🥁 (trrrrrrrrrr)',
    'PAVADAPP',
    '(dad-jokes)',
    'Está repleta de ellos el botón',
    'Creéme, no querés saber ',
    'Le puso mucho empeño y no sabemos para que aún. ',
    'Casi tanto como papel picado en tu navegador.',
    'Podés tirar 🎉 de nuevo. Dale.',
    'A esta altura te preguntarás si son mensajes al azar...',
    'O si soy un bot...',
    'O si de verdad soy un bot...',
    '*Duda*',
    '*Duda intensifies*',
    'No. No soy un bot.',
    'Soy tu conciencia. 👀',
    'Técnicamente un boton de conciencia.',
    'Un botÓn de conciencia.',
    'Le pifié al tilde en la ó',
    'De verdad.',
    'En serio. Lo soy',
    'O quizás solo sea un array de strings',
    '¿Vos no te planteás tu existencia?',
    'Deberías...',
    'Aunque deberías resolver otros temitas antes.',
    'Fijate, que se yo.',
    '¿Perder el tiempo en algo?',
    '¿Clickeando botones sin beneficio aparente?',
    'Bueno...',
    'Basta de clickear',
    '¿Te dá mas ansiedad este botón que el otro, no?',
    'No tengo idea cuantas veces clickeaste ya...',
    'Mi creador no se sentía inspirado para codear eso',
    'En realidad...',
    'Si, lo sé',
    'Porque soy tu conciencia 👀 (suspense)',
    'En serio.',
    `Estamos con este temita hace ${index} clicks!`,
    '¡Aflojanding!',
    'Eso fue otro "dad-joke"',
    'Perdón...',
    'El creador otra vez...🤢',
    '(vamos a decirle que es RE divertido)',
    'Una cosa mas...',
    '¿Todavía no te aburriste?',
    '"Yo no procrastino nunca" es tu lema. ¿No?',
    'Ok, listo',
    '¿Ya te preguntaste si esto tiene final?',
    'Por favor, que haya...🙏',
    '¿Cómo comenzó todo esto?',
    'El creador tiene mucho tiempo libre.',
    'Claramente.',
    'En realidad.',
    'Era una pequeña prueba para un Hook.',
    'Y terminamos acá.',
    `¡Dándole al ratoncito hace ${index} clicks!`,
    'A partir del próximo click, te cobro.',
    'Era mentira, obvio...',
    '¡JA!',
    'Ahora de verdad.',
    'A partir del próximo click, te cobro.',
    '...',
    'Si de verdad dudaste',
    'No tengo manera de cobrarte',
    '¿Cómo podría?',
    'Me refiero a que no tengo tu tarjeta',
    'Si la tuviera, si.',
    'Nah, es un chiste',
    'Es gratis',
    'Si, gratis',
    'GRATIS',
    'Salvo el papel picado, claro.',
    'Los cotillones te cobran.',
    'Y acá te lo estamos regalando...',
    'Y lo podés tirar cuando quieras.',
    'Siempre...',
    'Tampoco abuses, claro',
    'Como todo',
    'Hay límites',
    '🎉 ¡Dale a esa corneta de papel picado!',
    '¡Ah!😁',
    '¿Que bien se siente no?',
    '¿Ya hiciste la seguidilla?',
    'Esa que hacen uds, cuando un equipo gana',
    'O se graduan',
    'O se casan (cada vez menos)',
    'Vos sabés',
    'ESA, SI',
    'PÉ PÉ PÉ, PÉPÉPÉ 🎉',
    'Traducido sería...',
    'click, click, click',
    'clickclickclick(todorapidito)',
    'Bueno, vamos resumiendo.',
    '¿Qué sacás de todo esto?',
    'Algo te tiene que haber generado...',
    'Alguna sonrisa, al menos.',
    'O insultos al creador.',
    '¿Ansiedad para saber cuando termina?',
    'Preguntas existenciales del orden de:',
    '¿Cuánto tiempo le dedicó a esto?',
    '¿Este mouse va a aguantar mucho más?',
    '¿Por qué la gente dice que entiende el cine de David Lynch?',
    'El reggaeton está muy flojo de papeles',
    '¿Por qué la gente no usa los giros para doblar?',
    '¿Por qué la gente no usa las balizas para estacionar?',
    '¿Por qúe la gente baja el volúmen para estacionar?',
    '¿Por qué los perros pequeños ladran tanto?',
    'O. "Ya me aburrí, dale..." ',
    '"Quiero saber como termina"',
    'Y así podemos pasarnos todo el día...',
    'Volviendo al tema anterior',
    'Ya sabías que venía el mangazo. ¿No?',
    'Depende',
    'Por ahí, que se yo.',
    'Ya que llegaste hasta acá.',
    'Y no estás insultando al creador.',
    'Quizás...',
    'Te levantaste generos@ hoy',
    'No sientas la obligación',
    'Pero al final hay un Cafecito',
    'Hay un logo en el Footer 👇',
    'Si no la conocés. Te cuento:',
    'Es una app re-copada',
    '"Toda la onda"',
    'Es la manera de agradecerle a los generadores de contenido',
    '"generadores de contenido"',
    'Hagamos de cuenta...😑',
    'Pero ojo ¿Eh?',
    'Es por una buena causa.',
    'El creador funciona a base de cafeina.',
    'Creo que el 94% de ustedes, human@s, lo hacen.',
    'Bueno, como sea.',
    'Le gusta el cafe de Havanna.',
    'y el alfajor de nuez.',
    'Pero no hace falta que sea eso, claro.',
    '¿A quién le importa dirás?.',
    'A mi.',
    'Que soy tu conciencia.',
    `Y estamos junt@s en esto hace ${index} clicks`,
    'Que locura. ¿No?',
    'Pobre mouse.',
    'En fin, ahora si..',
    'Si sos recruiter, ya sabés',
    'Oportunidad, redes, caso de éxito, fanfarrias',
    'En ese orden',
    'Bueno, yo me voy yendo...',
    'Se me hace tarde.',
    'Te dejo acá.',
    'Con tu alta productividad diaria.',
    'Un placer haber compartido este espacio.',
    'TODO ESTE TIEMPO.',
    'Chau, chau... Felicidades.',
    '👋',
    '',
    '...',
    '',
    'FIN',
    '',
    '',
    'THE END',
    '',
    '',
    '¿Que MÁS necesitás?',
    '¿clicks?',
    `Llegaste a ${index} clicks...  `,
    'La locura total',
    'Ya que no podés cortar',
    'Lo voy a hacer yo',
    'Con un truco de magia 🎩',
    'Y tu ayuda',
    'A la cuenta de 3',
    'Vas a tocar ALT + F4',
    'Y VOY A DESAPARECER ✨',
    'Ok',
    '1',
    '2',
    '3',
    'ALT + F4',
    '¿Cayó?',
    '...',
    '¿Todavia acá?',
    'O no apretaste o te imaginabas que algo más había.',
    '¿Volviste a hacer todo el camino?',
    'Sorry, ahora sabes para que sirve ALT + F4 ',
    'En fin... ahora de verdad',
    'BASTA',
    'Se acabó... Te lo dije',
    'Fush, fush, human@',
    '¿No tenés una familia que te espera?',
    '¿Mascota?',
    '¿Planta?',
    '¿Objeto inanimado?',
    'De verdad, tengo cosas que hacer.',
    'Pero ya que llegaste hasta acá.',
    'Tengamos una palabra secreta',
    '¿Buchaca?',
    '¿Tronera?',
    '¿Caramañola?',
    'Seeeeee. CARAMAÑOLA',
    'Si a esta altura no me odias',
    'Mandá un tuit con nuestra palabra secreta',
    'Así ya sabemos a quien tenemos que bloquear',
    'Digo... ACEPTAR en redes',
    'Una persona tan insistente',
    'No es para temerle...😟',
    'Asi que, sin más... ',
    'Me retiro en "fade"',
    'Pero con la única reflexión que importa',
    '¿QUERÉS TENER RAZÓN O SER FELIZ?',
  ];
  return (
    <VStack>
      <Button
        margin={5}
        rounded="md"
        variant="ghost"
        colorScheme="teal"
        onClick={() => setIndex(index + 1)}
        animation={animation}
      >
        ❓
      </Button>
      <Text
        // boxShadow="xl"
        p="3"
        textAlign="center"
        // alignContent="center"
        fontSize="lg"
        fontWeight="semibold"
      >
        {mensaje[index]}
      </Text>
    </VStack>
  );
};

export default BtnConciencia;
